data_local: /home/itanh0b/llm-foundry/tokenized_datasets/ArabicText2022_arabic_llama3_2048_mds
data_remote: # If blank, files must be present in data_local
tokenizer_name: /home/itanh0b/llm-foundry/tokenizer/meta-Llama-3-8B-v32000-arabic
max_seq_len: 2048
global_seed: 17

# Run Name
run_name: llama3-arabictext2022 # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: hf_causal_lm
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3-8B
  use_flash_attention_2: true
  use_auth_token: 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
  pretrained: false

  config_overrides:
    attention_bias: false
    attention_dropout: 0.0
    bos_token_id: 0
    eos_token_id: 1
    hidden_act: silu
    hidden_size: 1024
    initializer_range: 0.02
    intermediate_size: 4096
    max_position_embeddings: 2048
    model_type: llama
    num_attention_heads: 16
    num_hidden_layers: 24
    num_key_value_heads: 16
    pretraining_tp: 1
    rms_norm_eps: 1e-05
    rope_scaling: null
    rope_theta: 500000.0
    tie_word_embeddings: false
    torch_dtype: bfloat16
    use_cache: true
    vocab_size: 32000

# Tokenizer
tokenizer:
  name: ${tokenizer_name}
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    shuffle: false
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 3.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 5ep
eval_interval: 20000ba
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 256

# System
seed: ${global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 16
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: true
log_to_console: true
console_log_interval: 1000ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  wandb:
    project: llm-foundry-scripts_train
# Checkpoint to local filesystem or remote object store
save_interval: 20000ba
save_num_checkpoints_to_keep: 100  # Important, this cleans up checkpoints saved to DISK
save_folder: ./{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt
